# This is a basic workflow to help you get started with Actions

name: Smoke Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_lab1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Install
        run: 
          sudo apt-get install gcc
      - name: Run shell test
        run: |
          chmod +x lab1/shell/shell-test.sh
          ./lab1/shell/shell-test.sh
          
      - name: Compile stress
        run: 
          gcc -o stress-test ./lab1/benchmark/stress-test.c
      - name: Compile search
        run: 
          gcc -o ema-search-str ./lab1/benchmark/ema-search-str.c
      - name: Compile path
        run: 
          gcc -o short-path ./lab1/benchmark/short-path.c


      - name: Run search test

        run: |
          SUBSTRING=$(cat lab1/benchmark/substring.txt)
          ./ema-search-str lab1/benchmark/test.txt "$SUBSTRING" 1 > output.txt 2>&1 || exit 1
          if [ -s output.txt ]; then
          echo "Test failed: Program produced output or error"
          cat output.txt
          exit 1
          fi

      - name: Run path test

        run: |
          ./short-path 1000 > output.txt 2>&1 || exit 1
          if [ -s output.txt ]; then
          echo "Test failed: Program produced output or error"
          cat output.txt
          exit 1
          fi

      - name: Run stress test

        run: |
          SUBSTRING=$(cat lab1/benchmark/substring.txt)
          ./stress-test lab1/benchmark/test.txt "$SUBSTRING" > output.txt 2>&1 || exit 1
          if [ -s output.txt ]; then
          echo "Test failed: Program produced output or error"
          cat output.txt
          exit 1
          fi

  test_lab2:

    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Install
        run:
          sudo apt-get install g++
      - name: Build library
        run:
            g++ -fPIC -shared -g -o liblab2.so lab2/lab2.cpp
      - name: Build ema-search-str
        run:
          g++ -g lab2/ema-search-str.cpp -L. -llab2 -o ema-search-str -lrt
      - name: Run test
        run:
          LD_LIBRARY_PATH=. ./ema-search-str lab2/test.txt ausf 1
